export function applyTheme(currentThemeColor) {
	document.documentElement.style.setProperty(
		'--bg-content-color',
		currentThemeColor.bgContentColor
	);
	document.documentElement.style.setProperty(
		'--border-box',
		currentThemeColor.borderBox
	);
	document.documentElement.style.setProperty(
		'--border-primary',
		currentThemeColor.borderPrimary
	);
	document.documentElement.style.setProperty(
		'--layout-bg',
		currentThemeColor.layoutBg
	);
	document.documentElement.style.setProperty(
		'--link-text-hover',
		currentThemeColor.linkTextHover
	);
	document.documentElement.style.setProperty(
		'--modal-scrollbar',
		currentThemeColor.modalScrollbar
	);
	document.documentElement.style.setProperty(
		'--player-bg',
		currentThemeColor.playerBg
	);
	document.documentElement.style.setProperty(
		'--purple-primary',
		currentThemeColor.purplePrimary
	);
	document.documentElement.style.setProperty(
		'--primary-bg',
		currentThemeColor.primaryBg
	);
	document.documentElement.style.setProperty(
		'--sidebar-popup-bg',
		currentThemeColor.sidebarPopupBg
	);
	document.documentElement.style.setProperty(
		'--text-color',
		currentThemeColor.textColor
	);
	document.documentElement.style.setProperty(
		'--text-item-hover',
		currentThemeColor.textItemHover
	);
	document.documentElement.style.setProperty(
		'--text-secondary',
		currentThemeColor.textSecondary
	);
	document.documentElement.style.setProperty(
		'--navigation-text',
		currentThemeColor.navigationText
	);
	document.documentElement.style.setProperty(
		'--placeholder-text',
		currentThemeColor.placeholderText
	);
}
